services:
  saltbot:
    build: .
    restart: unless-stopped
    environment:
      - TOKEN=${TOKEN}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - MUDAI_CHANNEL_ID=${MUDAI_CHANNEL_ID}
      - BIRTHDAY_CHANNEL_ID=${BIRTHDAY_CHANNEL_ID}
      - DATABASE_URL=${DATABASE_URL}
      - MUSIC_CHANNEL_ID=${MUSIC_CHANNEL_ID}
      - MODLOG_CHANNEL_ID=${MODLOG_CHANNEL_ID}
      - AUTOROLE_ID=${AUTOROLE_ID}
    volumes:
      - eggbot_data:/EggData

volumes:
  eggbot_data:
